version: '3.1'
services:
  anuglar:
    build: ./new-frontend/TaskTaskBoom
    ports:
      - "4200:80"
  api:
    build: ./backend/ProjektPraksa
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=myuser
      - POSTGRES_DB=mydb
    volumes:
      - ./db/startup.sql:/docker-entrypoint-initdb.d/startup.sql

    
